'use strict';
/* ---------- ANATOMY ---------- */
function bindAn(){S.an=Object.assign({},C.AN_DEFAULT,S.an);$('mode').value=S.mode;$('an_method').value=S.an.method;$('an_ratio').value=S.an.ratio;['smallM','quarterKm','eighthKm','sixteenthKm','bigM','cityKmh','osrmFactor'].forEach(k=>$('an_'+k).value=S.an[k])}
$('mode').onchange=e=>{S.mode=e.target.value;save()};
$('an_method').onchange=e=>{S.an.method=e.target.value;save()};$('an_ratio').oninput=e=>{const v=+e.target.value;if(v>=1.2){S.an.ratio=v;save()}};
['smallM','quarterKm','eighthKm','sixteenthKm','bigM','cityKmh','osrmFactor'].forEach(k=>$('an_'+k).oninput=e=>{const v=+e.target.value;if(v>0){S.an[k]=v;save()}});
const kmf=m=>f1(m/1000,1),mf=m=>Math.round(m).toLocaleString('en'),kph=v=>v?Math.round(v*3.6):'–';
function methodsSummary(A){
 const ev=A.evalTable||null,o={},prof=S.profiles[S.profileKey]||S.profiles.limit;
 C.METHODS.forEach(m=>{const cl=A.alt[m].clusters;let Lg=null,Lp=null;
  try{Lg=+C.computeRoute(C.segsForMethod(A,m,null),S.car,S.params,S.prices,prof).total.L.toFixed(2);if(A.probeRaw)Lp=+C.computeRoute(C.segsForMethod(A,m,A.probeRaw),S.car,S.params,S.prices,prof).total.L.toFixed(2)}catch(e){}
  o[m]={clusters:cl.length,eval:ev?ev[m]:null,litresGuess:Lg,litresProbed:Lp,partition:cl.map(c=>[c.a+1,c.b+1,c.g.hw[0]+(c.g.hw==='motorway'?'w':''),Math.round(c.len),Math.round(c.dur)])}});
 return o;
}
function crossModelMin(cl){if(!TL||!TL.curve)return null;return(C.curveAt(TL.curve,cl.endM,0,1)-C.curveAt(TL.curve,cl.startM,0,1))/60}
function crossTxt(cl,A){const m=crossModelMin(cl);return fmtDelta(cl.dur/60)+' · '+(m==null?'–':fmtDelta(m))}
function renderAnatomy(){
 const A=plan&&plan.analysis,el=$('anat');setTimeout(renderGraph,0);
 if(!A){el.innerHTML='<div class="sub">Plan a route to see its anatomy.</div>';return}
 const segOf=id=>segs.filter(s=>s.cluster===id);
 let h=`<div class="sub" style="margin-bottom:8px">${kmf(A.L)} km · ${A.steps.length} roads · ${A.clusters.length} clusters · longest road <b>${esc(A.longest)}</b> · shortest <b>${esc(A.shortest)}</b>${A.notes.length?' · '+esc(A.notes.join('; ')):''}</div>`;
 {const ms=methodsSummary(A);
  h+='<h3>Clustering methods compared <span class="sub">(active: '+A.method+' · ratio ×'+A.an.ratio+' · reference = OSM probes'+(A.evalTable?'':', not probed yet — run Smart mode')+')</span></h3><div class="scroll"><table><tr><th>method</th><th>clusters</th><th>class exact</th><th>within ±1</th><th>mean error (classes)</th><th>probes</th><th>L one way (guess)</th><th>L (probed)</th><th>idea</th></tr>'+C.METHODS.map(m=>{const e=ms[m].eval;return `<tr${m===A.method?' style="font-weight:600"':''}><td>${m}</td><td class="mono">${ms[m].clusters}</td><td class="mono">${e?e.exactPct+' %':'–'}</td><td class="mono">${e?e.nearPct+' %':'–'}</td><td class="mono">${e?e.meanErr:'–'}</td><td class="mono">${e?e.probes:'–'}</td><td class="mono">${ms[m].litresGuess==null?'–':f1(ms[m].litresGuess,2)}</td><td class="mono">${ms[m].litresProbed==null?'–':f1(ms[m].litresProbed,2)}</td><td class="sub" style="white-space:normal;min-width:240px">${esc(C.METHOD_INFO[m])}</td></tr>`}).join('')+'</table></div>';
  h+='<details style="margin:6px 0 10px"><summary>Where each method cuts (road numbers a–b, class letter)</summary>'+C.METHODS.map(m=>`<div class="sub"><b>${m}</b> · `+ms[m].partition.map(p=>p[0]+'–'+p[1]+' '+p[2]).join(' | ')+'</div>').join('')+'</details>';}
 h+='<h3>Clusters (guess → probe) · roads = number of turns</h3><div class="scroll"><table><tr><th>#</th><th>km</th><th>length</th><th>roads</th><th>median step</th><th>most common step</th><th>avg km/h</th><th>time to cross (OSRM · model)</th><th>% time / % km</th><th>kind</th><th>guess</th><th>conf.</th><th>final</th><th>→ next mid</th><th>→ 2nd next</th><th>roads</th></tr>'+A.clusters.map(cl=>{const ss=segOf(cl.id),s=ss[0];return `<tr><td class="mono">${cl.id}</td><td class="mono">${kmf(cl.startM)}–${kmf(cl.endM)}</td><td class="mono">${kmf(cl.len)} km</td><td class="mono">${cl.n}</td><td class="mono">${mf(cl.medLen)} m</td><td class="mono">${mf(cl.modeLen)} m ×${cl.modeN}</td><td class="mono">${kph(cl.avgV)}</td><td class="mono">${crossTxt(cl,A)}</td><td class="mono">${A.totT?Math.round(100*cl.dur/A.totT):'–'}% / ${Math.round(100*cl.len/A.L)}%</td><td style="white-space:normal;min-width:130px">${esc(cl.g.kind)}</td><td>${cl.g.hw}</td><td>${cl.g.conf}</td><td>${s?esc(s.hw)+(s.limit?' '+s.limit:'')+' <span class="sub">'+esc(s.src||'')+'</span>':'–'}</td>${[0,1].map(i=>{const b=cl.bridge[i];return `<td class="mono">${b?kmf(b.distM)+' km · '+Math.round(b.sec/60)+' min':'–'}</td>`}).join('')}<td class="sub" style="white-space:normal;min-width:160px" title="${esc(cl.g.why)}">${esc(cl.names.slice(0,2).join(', '))}</td></tr>`}).join('')+'</table></div>';
 h+='<h3 style="margin-top:12px">Where clusters change</h3><div class="scroll"><table><tr><th>km</th><th>to end</th><th>cluster</th><th>two roads before</th><th>two roads after</th></tr>'+A.deltas.map(d=>`<tr><td class="mono">${f1(d.kmFromStart)}</td><td class="mono">${f1(d.kmToEnd)}</td><td class="mono">${d.fromCl} → ${d.toCl}</td><td style="white-space:normal">${esc(d.before.join(' → '))}</td><td style="white-space:normal">${esc(d.after.join(' → '))}</td></tr>`).join('')+'</table></div>';
 h+='<h3 style="margin-top:12px">Checkpoints</h3><div class="scroll"><table><tr><th>what</th><th>km from start</th><th>min in</th><th>to end</th><th>road #</th><th>road</th><th>road length</th><th>km/h</th><th>to change ◂ ▸</th><th>before → after</th><th>guess</th><th>probe</th></tr>'+A.checkpoints.map(c=>`<tr><td>${esc(c.label)}</td><td class="mono">${f1(c.kmFromStart)}</td><td class="mono">${Math.round(c.minFromStart)}</td><td class="mono">${f1(c.kmToEnd)}</td><td class="mono">${c.roadNo}/${A.steps.length}</td><td>${esc(c.road)}</td><td class="mono">${mf(c.len)} m</td><td class="mono">${kph(c.v)}</td><td class="mono">${mf(c.toChangeBefore)} ◂ ▸ ${mf(c.toChangeAfter)} m</td><td style="white-space:normal" class="sub">${esc(c.prev||'start')} → ${esc(c.next||'end')}</td><td>${c.guess}</td><td>${c.probe?esc(c.probe.hw)+(c.probe.limit?' '+c.probe.limit:c.probe.unlimited?' none':''):'–'}</td></tr>`).join('')+'</table></div>';
 h+='<details style="margin-top:12px"><summary>All '+A.steps.length+' roads in order</summary><div class="scroll"><table><tr><th>#</th><th>road</th><th>km from start</th><th>to end</th><th>length</th><th>sec</th><th>km/h</th><th>cluster</th></tr>'+A.steps.map(s=>`<tr><td class="mono">${s.i+1}</td><td>${esc(s.label)}</td><td class="mono">${f1(s.startM/1000,2)}</td><td class="mono">${f1((A.L-s.startM)/1000,2)}</td><td class="mono">${mf(s.dist)} m</td><td class="mono">${Math.round(s.dur)}</td><td class="mono">${kph(s.v)}</td><td class="mono">${s.ci}</td></tr>`).join('')+'</table></div></details>';
 el.innerHTML=h;
}
function analysisJson(){
 const A=plan&&plan.analysis;if(!A)return '';
 const res={};if(segs.length)for(const k in S.profiles){const t=C.computeRoute(segs,S.car,S.params,S.prices,S.profiles[k]).total;res[k]={km:+t.km.toFixed(2),L:+t.L.toFixed(2),eur:+t.cost.toFixed(2),min:Math.round(t.sec/60)}}
 return JSON.stringify({app:'trip-fuel',when:new Date().toISOString(),places:plan.places||S.places,layers:{route:plan.routeLayer,roads:plan.classLayer},settings:{mode:S.mode,an:S.an},
  car:{mass:C.totalMass(S.car),Cd:+C.estimateCd(S.car).cd.toFixed(3),A:+C.frontalArea(S.car).toFixed(2),calib:S.params.calib},
  roads:A.steps.map(s=>[s.label,Math.round(s.dist),Math.round(s.dur),s.ci]),
  clusters:A.clusters.map(c=>({id:c.id,fromKm:+(c.startM/1000).toFixed(2),toKm:+(c.endM/1000).toFixed(2),roads:c.n,medianStepM:Math.round(c.medLen),avgKmh:Math.round(c.avgV*3.6),guess:c.g.hw,conf:c.g.conf,why:c.g.why})),
  deltas:A.deltas.map(d=>({km:+d.kmFromStart.toFixed(2),before:d.before,after:d.after})),
  methods:methodsSummary(A),activeMethod:A.method,checkpoints:A.checkpoints.map(c=>({key:c.key,km:+c.kmFromStart.toFixed(2),min:Math.round(c.minFromStart),roadNo:c.roadNo,road:c.road,lenM:Math.round(c.len),kmh:c.v?Math.round(c.v*3.6):null,guess:c.guess,probe:c.probe||null})),
  segments:segs.map(s=>({name:s.name,hw:s.hw,limit:s.limit,country:s.country,km:+(s.len/1000).toFixed(2),src:s.src||null})),results:res,levels:Object.fromEntries(Object.keys(levels).map(k=>{const T=C.computeRoute(levels[k],S.car,S.params,S.prices,S.profiles[S.profileKey]).total;return [k,{segments:levels[k].length,L:+T.L.toFixed(2),eur:+T.cost.toFixed(2),min:Math.round(T.sec/60)}]})),clusterDetail:A.clusters.map(c=>({id:c.id,kind:c.g.kind,turns:c.turns,bridge:c.bridge.map(b=>({to:b.to,km:+(b.distM/1000).toFixed(2),min:+(b.sec/60).toFixed(1)})),samples:c.samples.map(s=>({kind:s.kind,km:+s.km.toFixed(2)}))}))},null,1);
}
$('copyAna').onclick=async()=>{const j=analysisJson(),ta=$('anaJson');ta.value=j;ta.hidden=false;try{await navigator.clipboard.writeText(j);$('copyAna').textContent='Copied ✓'}catch(e){ta.select();$('copyAna').textContent='Select & copy below'}setTimeout(()=>$('copyAna').textContent='Copy analysis JSON',3000)};

